#!/bin/sh
# Warning: This script will be run by `sh(1)` no matter the shebang.{{{
#
# Do *not* use bashisms such as `[[` or `<<<`; you would get errors.
#
# `sshd(8)` passes the script to `sh(1)` as argument:
#
#     Running /bin/bash -c '/bin/sh /home/john/.ssh/rc'
#                           ^-----^
#
# That explains why the shebang is ignored, and why the script doesn't even need
# to be executable.
#
# BTW, the previous message can be read by connecting to an `sshd(8)` running in
# debug mode (one `-d` is enough; and no need of `-v` when starting the client).
#}}}

# The script should not produce any output on stdout; if necessary use stderr instead.{{{
#
#    > If the file ~/.ssh/rc exists, sh(1) runs it after reading the environment
#    > files but before starting the user's shell or command.  **It must not**
#    > **produce any output on stdout; stderr must be used instead.**
#
# Source: `man sshd /^SSHRC`
#}}}
# The script is meant to be run when you log on *this* local machine from a remote.{{{
#
# *Not* whenever you start a new SSH session to a remote.
#}}}
# The script is not run!{{{
#
# Make sure `PermitUserRC` is set to `yes` in `sshd_config`.
#}}}

# If this script is run, for X11 forwarding to work, we might need to run a `xauth(1)` command:{{{
#
#    > If X11 forwarding is in use, it will receive the "proto cookie" pair in its
#    > standard input (and DISPLAY in its environment).  **The script must call**
#    > **xauth(1) because sshd will not run xauth automatically to add X11 cookies.**
#
# Source: `man sshd /^SSHRC`
#
# Without, we might get this kind of error:
#
#     $ ssh -v -X -C <user>@<host>
#     $ xeyes
#     ...
#     X11 connection rejected because of wrong authentication.
#     ...
#     Error: Can't open display: localhost:10.0
#
# At least, we had this error once; but I can't reproduce it reliably.
#
# ---
#
# The purpose of  `$ xauth add ...` is to add an X11  cookie in `~/.Xauthority`.
# Without  this cookie,  the  local  X server  will  refuse  to start  graphical
# applications.
#}}}
if [ -n "$DISPLAY" ] && read -r proto cookie; then
  # That doesn't *seem*  necessary (i.e. we might get rid  of `$displayname` and
  # simply replace  it with `$DISPLAY` in  the next `xauth(1)` command)  but the
  # code at `man sshd /^SSHRC` does something like  this, so better be safe than
  # sorry.
  displayname="$(echo "$DISPLAY" | sed 's/^localhost:/unix:/')"
  xauth -q add "$displayname" "$proto" "$cookie"
fi
