vim.keymap.set('!', '<C-k>', function() require('readline').kill_line() end)
vim.keymap.set('!', '<C-u>', function() require('readline').backward_kill_line() end)
vim.keymap.set('!', '<M-d>', function() require('readline').kill_word() end)
vim.keymap.set('!', '<M-BS>',function() require('readline').backward_kill_word() end)
vim.keymap.set('!', '<C-w>', function() require('readline').unix_word_rubout() end)
vim.keymap.set('!', '<C-d>', function() require('readline').delete_char() end)
vim.keymap.set('!', '<C-h>', '<BS>')
vim.keymap.set('!', '<C-a>', function() require('readline').beginning_of_line() end)
vim.keymap.set('!', '<C-e>', function() require('readline').end_of_line() end)
vim.keymap.set('!', '<M-f>', function() require('readline').forward_word() end)
vim.keymap.set('!', '<M-b>', function() require('readline').backward_word() end)
vim.keymap.set('!', '<C-f>', '<Right>')
vim.keymap.set('!', '<C-b>', '<Left>')
vim.keymap.set('!', '<C-n>', '<Down>')
vim.keymap.set('!', '<C-p>', '<Up>')
vim.keymap.set('c', '<M-p>', function() return vim.fn.wildmenumode() == 0 and '<Up>' or '<Left>' end,
  { expr = true})
